name: helm-deployer
on: push
jobs:
  helm:
    name: Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main
      
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.3
      
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: default

      - name: Lint chart
        run: helm lint sample-go

      - name: Install release
        uses: hiberbee/github-action-helm@latest
        with:
          helm: upgrade --install --dry-run sample-go sample-go